### ISSUE TITLE
Use of jump

### ISSUE THREAD

**Issue by senioranalyst** [clint-tseng/odkbuild#25]
Instead of using groups every time you want to skip a group of questions, it would be easiest by using jumps. Example:
If answer is '2' in question q1 then jump to q12.
If answer is '2' or/and '3' in question q1 then jump to q12.
If answer is '1' in question q1 then terminate interview.
If answer is '2' in question q1  and '1' in question q2 then jump to q12.

**Comment by clint-tseng** [comment]
Jump vs skiplogic is something that's been debated back and forth a lot in the community. Most of the ODK toolchain is on the skiplogic side of things rather than jump, and so this tool follows suit. I can't implement any features that aren't already supported by the runtime (eg Collect).

I appreciate the feedback, though.
